Newest upgrade on offline mode
kougen/cpp-tic-tac-toe pull request #13
Opened 2024-01-25 22:11 UTC by SRPBerenyiM

2024-02-01 18:10 UTC, joshika39 requested changes
Add the `game.exe` and `game.o` to the .gitignore file

2024-02-01 18:10 UTC, joshika39 commented on game.exe
Remove the file!

2024-02-01 18:10 UTC, joshika39 commented on game.o
Remove the file!

2024-02-06 10:21 UTC, joshika39 requested changes

2024-02-06 10:21 UTC, joshika39 commented on game.exe
By Removing I mean, delete the .exe and push it that way!

2024-02-06 10:21 UTC, joshika39 commented on game.o
By Removing I mean, delete the .o and push it that way!

2024-02-06 11:18 UTC, SRPBerenyiM commented on game.o
I forgot how to do that.

2024-02-06 11:35 UTC, joshika39 commented on game.o
If you go to the project folder you will see a `game.cpp`, a `game.exe` and a `game.o`. Now, delete the `.exe` and the `.o` files. 

After you've deleted the files, go to Fork, and do a commit and a push as usual.

2024-02-06 11:39 UTC, joshika39 commented on game.o
Those two, yes.

2024-02-06 11:49 UTC, joshika39 approved these changes

2024-02-06 11:50 UTC, merged